import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alex's Blog",
  description: "Generated by create next app",
};

const header = (
  <header>
    <Link href="/">
      <h1 className="flex justify-center bold text-xl">Lux Articles</h1>
    </Link>
  </header>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
      </body>
    </html>
  );
}
